version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ComunaTec"
    assignees:
      - "ComunaTec"
    commit-message:
      prefix: "security"
      include: "scope"
    labels:
      - "security"
      - "dependencies"
    ignore:
      # Ignore major version updates for now
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Group updates for related packages
    groups:
      flask:
        patterns:
          - "flask*"
          - "werkzeug*"
          - "itsdangerous*"
          - "markupsafe*"
      security:
        patterns:
          - "bcrypt*"
          - "cryptography*"
          - "pyjwt*"
      redis:
        patterns:
          - "redis*"
